import { GENRES } from "@/lib/constants";

export const faqItems = [
  {
    question: "Does it cost anything to submit?",
    answer:
      "No. There is no submission fee. Submitting a project does not create a distribution relationship or obligation on either side.",
  },
  {
    question: "Do I pay for poster or trailer work upfront?",
    answer:
      "No. For accepted titles, packaging support we agree to invest in the release is not billed to you as an upfront invoice. Scope and spend are set per film with you, then written into the agreement. That investment is recouped only from revenue generated by the film, as defined in the signed distribution agreement.",
  },
  {
    question: "What happens if the film never recoups?",
    answer:
      "A title may never generate enough receipts to recoup the agreed packaging investment or other contract-defined expenses. Filmmakers are not personally obligated to repay that agreed investment unless a separate written arrangement explicitly states otherwise. Silver Spring Studios accepts that commercial risk as part of the partnership model.",
  },
  {
    question: "Is acceptance guaranteed?",
    answer:
      "No. Silver Spring Studios is selective and reviews each submission on its own merits. Submission, review or conversation does not guarantee an offer, and an offer does not guarantee that both parties will proceed to a signed agreement.",
  },
  {
    question: "Can you guarantee placement on specific platforms?",
    answer:
      "No. Platform availability, licensing terms and placement vary by title, rights, territory and market conditions. We do not guarantee placement on any specific platform, service or territory.",
  },
  {
    question: "What genres do you distribute?",
    answer: `Our current acquisition focus includes ${GENRES.slice(0, -1).join(", ")} and ${GENRES[GENRES.length - 1]}. We are most interested in completed work with clear genre positioning and a commercially identifiable audience, though we may consider distinctive projects outside these categories.`,
  },
  {
    question: "Do you accept short films?",
    answer:
      "Our primary focus is completed feature films, documentaries and limited series. Short films are generally outside our current acquisition scope unless submitted as part of a broader rights package discussed during review.",
  },
  {
    question: "Do you accept films that have already been released?",
    answer:
      "Yes, in some cases. We consider prior festival, theatrical, digital or self-release history as part of review. Available rights, existing agreements and remaining commercial potential must be clear before any offer can be considered.",
  },
  {
    question: "What rights do you require?",
    answer:
      "Required rights vary by project, territory and release strategy. During review we discuss which exploitation rights may be needed for the proposed release. Exact rights grants, reservations, holdbacks and reversion terms are specified only in a written distribution agreement.",
  },
  {
    question: "How long is the distribution term?",
    answer:
      "Term length is project-specific. Duration, renewal options, reversion triggers and post-term obligations are disclosed during discussions with promising projects and defined in the signed agreement. We do not apply a single standard term to every title.",
  },
  {
    question: "How often do filmmakers receive reports?",
    answer:
      "Reporting frequency and format are defined in each distribution agreement. We aim to provide scheduled revenue statements and direct communication so filmmakers can understand earnings, deductions and recoupment status throughout the term.",
  },
  {
    question: "Can I submit without a finished trailer or poster?",
    answer:
      "Yes. A private screener is the essential material for initial review. Trailer and key-art materials are helpful but not required to submit. If a project advances, we discuss which existing materials are usable and what release assets may be prepared.",
  },
  {
    question: "Do you accept international films?",
    answer:
      "Yes. We consider English-language productions and select international titles, particularly from Canada, the United States and other territories where we can realistically license and support a release. Subtitle availability and rights clarity are important factors in review.",
  },
  {
    question: "Do I need an entertainment lawyer?",
    answer:
      "We recommend that filmmakers consult independent legal counsel before signing any distribution agreement. Silver Spring Studios may provide a draft agreement for review, but each party should satisfy itself that the terms are understood and appropriate.",
  },
  {
    question: "What deliverables will I need?",
    answer:
      "Deliverable requirements depend on the film's format, audio configuration, existing materials and planned exploitation. Typical items may include a master file, caption files, metadata, stills and chain-of-title documentation. Exact technical and legal deliverables are confirmed during onboarding and listed in the signed agreement.",
  },
] as const;
