import { PageHero } from "@/components/layout/PageHero";
import { BreadcrumbJsonLd, createMetadata } from "@/components/seo/metadata";
import { ButtonLink } from "@/components/ui/ButtonLink";
import { Section, SectionHeader } from "@/components/ui/Section";
import { STUDIO_ADVISOR } from "@/lib/studio-advisor";

export const metadata = createMetadata({
  title: "How It Works",
  description:
    "From first submission to signed release: how Silver Spring Studios evaluates completed independent films and prepares selective distribution partnerships.",
  path: "/how-it-works",
});

const steps = [
  {
    number: "01",
    title: "Submit",
    summary: "Tell us about the film and provide a private screener.",
    detail:
      "Complete the submission form with filmmaker details, rights information, materials and release expectations. Include a secure screener link and any supporting context that helps us understand the audience, positioning and rights position. Submission is free. It does not create a distribution agreement.",
  },
  {
    number: "02",
    title: "Review",
    summary: "Our acquisitions team evaluates the project, materials and commercial fit.",
    detail:
      "We watch the screener, review chain-of-title readiness, assess technical quality and consider whether the film has a clear audience and release path. Not every submission advances. We may request additional information, schedule a conversation or respectfully decline when a project is not the right fit.",
  },
  {
    number: "03",
    title: "Discuss",
    summary: "Promising projects receive a direct conversation about strategy and terms.",
    detail:
      "If we see potential for a partnership, we speak with the filmmaker about release goals, available rights, realistic expectations and the standard release investment model. This is a working conversation—not a sales pitch. We prefer honest assessment over enthusiasm without substance.",
  },
  {
    number: "04",
    title: "Agreement",
    summary: "A release begins only after a written agreement is reviewed and signed.",
    detail:
      "When both sides wish to proceed, we prepare project-specific terms covering territories, term, recoupment, reporting and deliverables. Nothing is guaranteed until a signed distribution agreement is in place. Filmmakers are encouraged to involve counsel before signing.",
  },
];

const afterSigning = [
  {
    title: "Onboarding and deliverables",
    body: "We confirm masters, captions, key art needs, metadata and any remaining clearance items required for release preparation.",
  },
  {
    title: "Release preparation",
    body: "Selected projects may receive positioning, poster design, trailer editing, EPK support, platform preparation and publicity coordination—tailored to the film, not applied as a generic package.",
  },
  {
    title: "Distribution and reporting",
    body: "We pursue licensing and release opportunities appropriate to the film. Revenue, deductions and recoupment are reported according to the signed agreement. Platform placement and earnings are never guaranteed.",
  },
  {
    title: "Recoupment and receipts",
    body: "The agreed release investment is recouped from net receipts generated by the film. After recoupment, distributable receipts are shared according to the signed agreement—typically 60% to the filmmaker and 40% to Silver Spring Studios on net receipts, subject to contract.",
  },
];

export default function HowItWorksPage() {
  return (
    <>
      <BreadcrumbJsonLd
        items={[
          { name: "Home", path: "/" },
          { name: "How It Works", path: "/how-it-works" },
        ]}
      />

      <PageHero
        eyebrow="Process"
        title="How it works"
        description={`A selective path from submission to release—built on review, conversation and a signed agreement. ${STUDIO_ADVISOR.responseAimLabel}. Acceptance is never guaranteed.`}
      />

      <Section tone="elevated">
        <SectionHeader
          eyebrow="Four steps"
          title="From screener to signed release"
          description="Each stage is designed to respect your time and give both sides enough information to decide whether a partnership makes sense."
        />

        <ol className="space-y-0 divide-y divide-line">
          {steps.map((step) => (
            <li key={step.number} className="grid gap-6 py-10 md:grid-cols-[5rem_1fr] md:gap-10 md:py-12">
              <p className="font-display text-3xl text-warm-metal md:text-4xl">{step.number}</p>
              <div>
                <h3 className="font-display text-2xl text-ivory md:text-3xl">{step.title}</h3>
                <p className="mt-2 text-sm tracking-[0.08em] uppercase text-silver">{step.summary}</p>
                <p className="mt-5 max-w-3xl text-base leading-relaxed text-slate">{step.detail}</p>
              </div>
            </li>
          ))}
        </ol>
      </Section>

      <Section>
        <SectionHeader
          eyebrow="After signing"
          title="What happens once an agreement is in place"
          description="Release work is collaborative. The exact scope, timeline and services depend on the film and the signed agreement."
        />

        <div className="grid gap-10 md:grid-cols-2">
          {afterSigning.map((item) => (
            <article key={item.title} className="border-t border-line-strong pt-8">
              <h3 className="font-display text-xl text-ivory">{item.title}</h3>
              <p className="mt-4 text-sm leading-relaxed text-slate">{item.body}</p>
            </article>
          ))}
        </div>

        <p className="mt-12 max-w-3xl text-sm leading-relaxed text-slate">
          A film may never generate enough revenue to recoup the agreed release investment. We do not
          ask filmmakers to personally repay the standard release investment unless separately agreed
          in writing. Final financial terms, territories, term and reporting are always governed by
          the signed distribution agreement.
        </p>
      </Section>

      <Section tone="ivory">
        <div className="flex flex-col gap-8 md:flex-row md:items-end md:justify-between">
          <div className="max-w-2xl">
            <SectionHeader
              light
              eyebrow="Ready when you are"
              title="Submit a completed film for consideration"
              description="If you have a finished feature, documentary or limited series with clear rights, we would like to hear from you."
            />
          </div>
          <div className="flex flex-wrap gap-4">
            <ButtonLink href="/submit" variant="primary">
              Submit Your Film
            </ButtonLink>
            <ButtonLink href="/filmmakers" variant="secondary" className="border-ink/20 text-ink hover:border-ink">
              For Filmmakers
            </ButtonLink>
          </div>
        </div>
      </Section>
    </>
  );
}
