export type ChecklistSection = {
  id: string;
  title: string;
  items: string[];
};

export const CHECKLIST_SECTIONS: ChecklistSection[] = [
  {
    id: "rights",
    title: "Rights",
    items: [
      "Confirm you control or have licensed all rights necessary for digital distribution in the territories you plan to grant.",
      "Collect chain-of-title documentation from development through final cut (option agreements, assignments, WFH confirmations).",
      "List any third-party content in the film (archival footage, news clips, trademarks, artwork) with license status for each item.",
      "Document whether the film has prior distribution, broadcast, or exclusive windows that would conflict with a new deal.",
      "Identify whether any financier, bond company, or executive producer holds approval or distribution veto rights.",
      "Prepare a one-page rights summary a distributor can read without parsing a folder of unscanned PDFs.",
      "Flag known encumbrances honestly — unresolved claims are a meeting-stopper, not a footnote to clarify later.",
    ],
  },
  {
    id: "music",
    title: "Music",
    items: [
      "Separate score, source music, and soundtrack album rights — they are often owned or licensed differently.",
      "Obtain sync and master-use licenses (or verify composer work-for-hire / score ownership) for every cue in the final cut.",
      "Prepare a music cue sheet with timecode in/out, song title, composer, publisher, and PRO affiliation for each use.",
      "Confirm whether any festival-only music permissions expire before digital release and budget re-licensing if needed.",
      "Check that temp tracks from editing did not accidentally remain in the picture-locked master.",
      "Document any royalty-free or library licenses with proof of purchase and permitted usage scope.",
      "If a soundtrack release is planned, clarify whether those rights were reserved or included in the film license.",
    ],
  },
  {
    id: "cast-and-crew-agreements",
    title: "Cast and crew agreements",
    items: [
      "Collect signed performer releases granting use of name, likeness, voice, and performance in the finished film and its promotion.",
      "Verify director, producer, and key crew agreements assign copyright or grant distribution rights as intended.",
      "Confirm minors have guardian-signed releases and any required jurisdictional compliance (Coogan accounts where applicable).",
      "Document deferred payment, profit participation, and backend definitions so a distributor understands existing obligations.",
      "Ensure SAG-AFTRA, ACTRA, or other union status is disclosed with signatory paperwork and residual obligations noted.",
      "Obtain clearance for improvised dialogue, crowd shots, and background performers where identifiable.",
      "Align on-screen credits with contractual credit obligations before locking metadata for release.",
    ],
  },
  {
    id: "master-files",
    title: "Master files",
    items: [
      "Deliver a picture-locked master at the agreed aspect ratio — typically 23.976 or 24 fps ProRes 422 HQ or platform-specified codec.",
      "Provide separate full-resolution master without burned-in captions (textless) when captions will be supplied as sidecar files.",
      "Confirm color grade is finalized on a broadcast-safe monitor; avoid illegal levels and unintended oversaturation on streaming transcodes.",
      "Include slate with correct runtime, title, episode number (if applicable), and audio configuration at head or in delivery notes.",
      "Verify the screener link matches the master runtime and content — no alternate cuts without disclosure.",
      "Archive project files and color timeline separately; distributors need delivery masters, not editable timelines, unless contracted.",
      "Run a full playback QC pass for drop frames, digital hits, compression artifacts, and reel-change errors before submission.",
    ],
  },
  {
    id: "audio",
    title: "Audio",
    items: [
      "Deliver discrete stereo or 5.1 mixes per platform spec; document which mix is primary for streaming delivery.",
      "Meet loudness targets appropriate for streaming (commonly near -24 LKFS for stereo long-form with true peak headroom).",
      "Provide M&E (music and effects) stems when required for international or accessibility dubbing workflows.",
      "Ensure dialogue is intelligible on laptop speakers — a common QC failure for otherwise strong festival mixes.",
      "Confirm all ADR, voice-over, and archival audio is synced and level-matched across reels.",
      "List audio sample rate and bit depth in delivery notes (e.g., 48 kHz, 24-bit).",
      "Remove editor reference tones, slate mics, and channel identification mistakes from the final print master.",
    ],
  },
  {
    id: "captions",
    title: "Captions",
    items: [
      "Prepare English SDH (subtitles for the deaf and hard of hearing) with speaker IDs, sound effects, and accurate timing.",
      "Supply captions as .srt or .vtt sidecars synchronized to the final master timecode, not a festival screener cut.",
      "Proofread for spelling, homophones, and line breaks — auto-generated captions rarely pass distributor QC without review.",
      "Confirm forced-narrative subtitles for foreign-language dialogue if present, separate from full SDH files where required.",
      "Document whether additional language subtitles exist and which territories they cover.",
      "Verify caption readability at phone scale (line length, reading speed, contrast assumptions for burned-in exports if any).",
      "Keep a revision log if captions are updated after festival screenings to match dialogue changes.",
    ],
  },
  {
    id: "artwork",
    title: "Artwork",
    items: [
      "Provide a high-resolution key art file (typically 300 DPI minimum at one-sheet dimensions, or vector where possible).",
      "Deliver layered or textless poster variants when contractually required for localized marketing.",
      "Supply stills at platform minimum resolution (often 1920×1080 or higher) with signed releases for recognizable people.",
      "Include a clear title treatment that remains legible at thumbnail scale — test at 200 px wide before submission.",
      "Avoid festival laurels on primary key art unless you have confirmed rights and the laurel is current for release positioning.",
      "Prepare banner and social crop-safe compositions; a one-sheet alone is rarely enough for full platform art packages.",
      "Confirm font and stock-image licenses permit commercial distribution use in all granted territories.",
    ],
  },
  {
    id: "trailer",
    title: "Trailer",
    items: [
      "Provide a release-ready trailer or sufficient source material (selects, stems, project files) if trailer support is part of the deal.",
      "Match trailer aspect ratio and resolution to platform specs; avoid letterboxed festival bumpers in the deliverable.",
      "Clear music in the trailer separately — trailer sync licenses do not automatically transfer from the feature.",
      "Include timed captions or a captioned trailer file when the main feature ships with SDH.",
      "Keep runtime appropriate for browse contexts (often 60–120 seconds for indie feature trailers unless platform requests otherwise).",
      "Avoid major spoilers unless intentionally positioned; acquisitions uses trailers to judge marketability, not plot summary.",
      "Document whether the trailer is filmmaker-supplied final or a work-in-progress for distributor editorial support.",
    ],
  },
  {
    id: "metadata",
    title: "Metadata",
    items: [
      "Lock official title, year, country of origin, runtime, and language before distributor metadata entry — changes after go-live are costly.",
      "Write a consumer-facing synopsis (often 250–400 characters for browse cards) distinct from your festival program note.",
      "Prepare a long synopsis, director statement, and cast/crew list with consistent spelling and billing order.",
      "Select primary and secondary genres honestly; miscategorized horror/drama hybrids frustrate platform algorithms and reviewers.",
      "List content advisories accurately (violence, language, nudity) to match platform rating questionnaires.",
      "Provide IMDb or reference links only if credits and runtime already match the delivery master.",
      "Include keywords and comparables as positioning notes, not as guarantees of placement alongside those titles.",
    ],
  },
  {
    id: "festival-history",
    title: "Festival history",
    items: [
      "Maintain a current list of selections, awards, and premiere status with dates and official festival names spelled correctly.",
      "Clarify whether any festival sale, broadcast, or VOD window created exclusivity that affects digital launch timing.",
      "Distinguish between official selection and market screenings — acquisitions teams notice the difference.",
      "Gather press quotes and laurel artwork only if festivals grant promotional use rights in writing.",
      "Note upcoming festival dates that might conflict with a distributor’s planned release window.",
      "If the film screened from a DCP or H.264 screener unlike the final master, disclose post-festival finishing work remaining.",
      "Avoid implying worldwide premiere status if any prior public exhibition occurred online, on broadcast, or in another territory.",
    ],
  },
  {
    id: "press",
    title: "Press",
    items: [
      "Compile existing reviews, interviews, and feature articles with publication names, dates, and linkable URLs where permitted.",
      "Prepare a one-page EPK: logline, synopsis, director bio, cast highlights, production notes, and contact information.",
      "Identify whether a unit publicist, festival publicist, or sales agent still holds embargoed materials or approval rights.",
      "List outreach already completed so a distributor does not duplicate pitches journalists already declined.",
      "Gather high-res production photos with credit lines and photographer permission for commercial use.",
      "Separate verifiable metrics (article count, notable outlets) from aspirational marketing language in your submission.",
      "If no press exists yet, state that plainly and note realistic hooks for post-acquisition outreach rather than inventing buzz.",
    ],
  },
  {
    id: "audience-information",
    title: "Audience information",
    items: [
      "Describe the target audience in specific terms (age band, genre affinity, comparable titles) rather than “everyone who likes good movies.”",
      "Share verifiable data if available: newsletter size, social following by platform, email open rates, or crowdfunding backer count.",
      "Document festival Q&A turnout, sold-out screenings, or community screenings with approximate attendance — not extrapolated totals.",
      "Identify existing fan communities (genre forums, local markets, diaspora audiences) the release could credibly reach.",
      "Disclose prior self-distribution attempts, Vimeo-on-Demand runs, or YouTube availability and their performance honestly.",
      "Note cast or subject social reach separately from the film’s owned channels — reach does not equal conversion.",
      "Align audience claims with the film’s rating, language, and cultural specificity; niche films benefit from narrow targeting.",
    ],
  },
  {
    id: "existing-licensing",
    title: "Existing licensing",
    items: [
      "List all current and expired licenses: SVOD, AVOD, TVOD, educational, airline, hotel, or territorial sub-licenses.",
      "Provide copies or summaries of existing distribution agreements showing term end dates and exclusivity scope.",
      "Identify sales-agent holds, producer rep mandates, or co-production partner approval requirements still in effect.",
      "Document music sync deals, image licenses, and product placements with expiration or territory limits.",
      "Clarify whether any crowdfunding rewards promised digital copies or early access that could conflict with exclusive windows.",
      "Note if a soundtrack, remake, or format rights were previously licensed or retained by a third party.",
      "If the film is on FilmHub or another aggregator, disclose platform status and termination requirements before signing elsewhere.",
    ],
  },
  {
    id: "financial-obligations",
    title: "Financial obligations",
    items: [
      "Summarize outstanding deferments, backend participation, and waterfall priorities owed to cast, crew, or financiers.",
      "Disclose completion bond, insurance claim, or tax incentive clawback conditions that could affect receipt flow.",
      "Identify whether any investor expects gross participation before distributor recoupment — a common deal complication.",
      "Document P&A commitments, personal guarantees, or festival fees still unpaid that create production-company pressure.",
      "Clarify who receives revenue payments under the proposed deal (production entity, LLC, individual filmmaker).",
      "Provide tax forms readiness (W-9, W-8BEN) for the payee entity before first accounting period closes.",
      "Understand that distributor recoupment of an agreed packaging investment typically precedes filmmaker share of distributable receipts — exact caps and splits are deal-specific.",
    ],
  },
  {
    id: "release-goals",
    title: "Release goals",
    items: [
      "State whether your primary goal is revenue, audience reach, credential-building, or financier recoupment — they are not interchangeable.",
      "Identify preferred timing constraints (award season, anniversary, cast availability) and immovable conflicts.",
      "Clarify territory ambitions (North America only vs. worldwide) and whether you understand platform-by-platform variance.",
      "Specify format priorities: SVOD premiere, TVOD rental window, AVOD ad-supported, or non-exclusive educational alongside digital.",
      "Acknowledge that no distributor can guarantee platform placement, critic reviews, or minimum revenue.",
      "Define success metrics you will actually track (first-quarter gross, email list growth, review count) rather than vague “breakout” hopes.",
      "Confirm you have budget and bandwidth to support a release (interviews, social assets, fan outreach) if the distributor invests in packaging.",
    ],
  },
];
