import type { ResourceHub } from "./types";

export const RESOURCE_HUBS: ResourceHub[] = [
  {
    slug: "film-distribution",
    title: "Film Distribution",
    description:
      "How boutique digital distribution works for completed independent films — from evaluation through release, without pretending every title earns the same outcome.",
    longDescription:
      "Independent film distribution is not a single switch you flip after a festival premiere. It is a sequence of decisions about rights, positioning, deliverables, platform fit, and the economics of a release that may or may not recoup its costs. Silver Spring Studios works with finished films where the creative work is largely done but the commercial packaging often is not.\n\nThis hub covers what a real distributor evaluates before offering terms, how digital release differs from theatrical ambition, and why “getting on platforms” is a deliverables and metadata problem as much as a relationship problem. We write for filmmakers who want operational clarity — not a sales pitch disguised as education.\n\nNothing here guarantees acceptance, placement, review coverage, or revenue. It explains how a small studio thinks so you can compare offers, prepare materials, and enter conversations with eyes open.",
  },
  {
    slug: "deliverables",
    title: "Deliverables",
    description:
      "Master files, captions, artwork, metadata, and chain-of-title documents distributors actually need before a title can go live — with specs that reduce rework.",
    longDescription:
      "Most release delays are not dramatic rights disputes; they are missing ProRes masters, wrong aspect ratios, music cue sheets that do not match the final cut, or poster art that cannot scale to platform thumbnail requirements. Deliverables are where a film’s festival polish meets the unforgiving standards of aggregators and retailers.\n\nThis hub translates common platform and aggregator expectations into a practical checklist. We focus on what slows onboarding, what triggers QC failures, and what acquisitions teams flag during initial review. Specs vary by platform, but the underlying pattern is consistent: clean masters, documented rights, complete metadata, and assets that survive both 27-inch monitors and phone-sized browse grids.\n\nUse these guides alongside your own post supervisor and legal counsel. Distributors can describe requirements; filmmakers remain responsible for certifying that what they deliver is accurate and licensed.",
  },
  {
    slug: "revenue-recoupment",
    title: "Revenue & Recoupment",
    description:
      "How gross receipts become distributable receipts, why recoupment order matters, and how packaging investment is recovered in a typical indie digital deal.",
    longDescription:
      "Filmmakers hear a headline split and assume it applies to every dollar the film earns. It usually does not. Most indie digital deals apply a waterfall: platform fees and direct release expenses come out first, then the distributor’s agreed packaging investment is recouped from what remains, and only then is the balance split between filmmaker and studio as written in the agreement.\n\nAt Silver Spring Studios, packaging support we agree to invest for an accepted title is recouped from revenue generated by the film, not invoiced upfront to the filmmaker. Scope and spend are title-specific. That structure is straightforward on paper and easy to misunderstand when receipts are slow, reporting cycles lag, or “gross” and “distributable” are used interchangeably in conversation.\n\nThis hub walks through definitions, recoupment order, and reporting red flags without treating planning estimates as promises. Read it before you sign so you know what must happen before your share begins.",
  },
  {
    slug: "film-marketing",
    title: "Film Marketing",
    description:
      "Realistic publicity, audience targeting, and campaign assets for micro-budget releases — what a boutique distributor can execute and what still depends on the film and filmmaker.",
    longDescription:
      "Marketing an independent film without a studio publicity machine means choosing a narrow audience, a credible hook, and assets that earn attention in crowded browse environments. A distributor can support trailer editing, key art, and targeted outreach, but no campaign overcomes a unclear positioning statement or a film with no identifiable audience.\n\nThis hub covers how acquisitions teams think about marketability before offer, what materials matter at submission versus at release, and how publicity support in a standard release package differs from a guaranteed review or placement campaign. We are interested in campaigns that match the film’s scale — not fantasy billboards for titles with no awareness path.\n\nMarketing guidance here complements deliverables and poster/trailer hubs. Strong release creative is not decoration; it is often the first signal that a finished film can be packaged for digital shelves.",
  },
  {
    slug: "distribution-contracts",
    title: "Distribution Contracts",
    description:
      "Clause-by-clause guidance on term, territory, exclusivity, reporting, recoupment, and delivery — written for filmmakers reviewing their first or fifth distribution agreement.",
    longDescription:
      "A distribution agreement is an operating manual for a multi-year relationship, not a formality after a handshake. The sections that matter most — grant of rights, term and holdbacks, delivery specifications, recoupment definitions, accounting statements, and termination — determine what you can do with your film while it is under contract and what happens if the release underperforms.\n\nThis hub highlights language acquisitions editors expect to see, common asymmetries in indie deals, and questions worth asking before you sign exclusivity away. We reference structures aligned with Silver Spring Studios’ standard offer, but the principles apply broadly to digital distribution conversations.\n\nWe are not your lawyer. These articles help you read a draft with focus so legal review can be efficient. Bring defined terms, red-flag clauses, and specific questions — not a vague sense that the deal “feels fine.”",
  },
  {
    slug: "filmhub",
    title: "FilmHub & Aggregators",
    description:
      "How aggregator-led digital distribution fits — and does not fit — boutique release models, QC expectations, and when a curated distributor adds value beyond upload access.",
    longDescription:
      "FilmHub and similar aggregators give filmmakers a path to major platforms without a traditional distributor intermediary. That access is real, but it is not the same as curated positioning, release investment, deliverables support, or a partner screening submissions before committing resources.\n\nThis hub compares aggregator self-service release with boutique distribution on dimensions that matter operationally: QC burden, metadata ownership, marketing support, recoupment structures, and what happens when a title needs creative repositioning after a festival run. We do not treat aggregators as inferior — they solve a different problem for a different filmmaker at a different stage.\n\nIf you are deciding between uploading yourself and signing with a small studio, read here first. The right choice depends on your deliverables readiness, rights cleanliness, and whether you want release packaging treated as a collaborative discipline or a technical upload task.",
  },
  {
    slug: "festival-to-distribution",
    title: "Festival to Distribution",
    description:
      "What changes after the laurels fade — timing, screener strategy, heat versus readiness, and how festival buzz translates (or fails to translate) into a digital release plan.",
    longDescription:
      "A festival selection validates taste and can generate press, but it does not automatically produce a deliverables-ready master, clean music rights, or a commercial positioning statement distributors can act on. Many strong festival films stall in the gap between audience applause and release onboarding — not because the work lacks merit, but because the next phase requires different materials and different honesty about audience size.\n\nThis hub addresses post-festival decision windows, when to widen screener access, how to talk about awards without overstating market impact, and what acquisitions teams need once the premiere weekend is over. We write for filmmakers navigating inbound interest, conflicting advice, and the pressure to “strike while the iron is hot.”\n\nFestival success can open doors. It does not remove the need for rights documentation, realistic revenue expectations, or a release plan matched to the film’s actual commercial profile.",
  },
  {
    slug: "poster-and-trailer",
    title: "Poster & Trailer",
    description:
      "Key art and trailer craft for digital discovery — specs, creative direction, and why acquisitions teams treat packaging as an early signal of release readiness.",
    longDescription:
      "On most digital platforms, your poster renders at thumbnail scale before anyone reads a synopsis. A trailer is often the second decision point — not a mini-film, but a compressed argument for why a stranger should commit ninety minutes. Weak packaging does not always mean a weak film, but it routinely means a slower acquisition review and a harder release path.\n\nSilver Spring Studios invests in poster and trailer support for selected titles at a level agreed with the filmmaker — not a fixed public price for every film. This hub explains what strong key art and editorial trailers accomplish in a boutique digital release, what source materials filmmakers should provide, and how creative choices interact with genre expectations and platform browse behavior.\n\nThese articles are for filmmakers preparing materials before submission as well as those revisiting festival one-sheets that will not survive a digital shelf. Good packaging is not misleading hype — it is accurate positioning made visible.",
  },
  {
    slug: "submission-checklist",
    title: "Submission Checklist",
    description:
      "A practical pre-submission audit covering rights, masters, music, cast agreements, and release goals — so your application reflects how ready the film actually is.",
    longDescription:
      "Submissions move faster when the film’s materials tell a consistent story: the screener matches the claimed runtime, the rights answers align with the music heard on screen, and the filmmaker’s release expectations fit the film’s scale. Incomplete submissions do not always receive an immediate decline — but they often receive a delay, a needs-information request, or a meeting postponed until gaps are closed.\n\nThis hub organizes the pre-submission audit Silver Spring Studios recommends before you apply. It mirrors the questions our acquisitions team asks during initial review and the deliverables gaps that most commonly surface after an offer. Use it as a working document with your producer, post supervisor, and legal counsel.\n\nChecking boxes here does not guarantee acceptance. It reduces friction, surfaces deal-breaking issues early, and helps you present a finished film as a release-ready project rather than a work-in-progress with festival potential.",
  },
];

export function getHubBySlug(slug: string): ResourceHub | undefined {
  return RESOURCE_HUBS.find((hub) => hub.slug === slug);
}
